### ISSUE TITLE
Doesn't work with student who are in academic suspension

### ISSUE THREAD

**Issue by Pezhin** [719Ben/myCUinfo-API#3]
My friend fails courses during freshmen year and are taking special course this semester. The schedule in mycuinfo looks like this:
![a0f5f26f-66e2-4b7a-954f-1b9496d7417e](https://cloud.githubusercontent.com/assets/11862132/9700849/3fdbf976-53d0-11e5-8ea4-20942829f661.png)

This fails python with a error 

```
      tempClass["startTime"] = dateAndTime[1].split("<")[0]
 IndexError: list index out of range
```

**Comment by biw** [comment]
Could you post the whole schedule including Course Site, Credits, Status,
and Grade?

**Comment by biw** [comment]
Not sure if this is still an issue, if it is, please comment again and we can open it back up.
