### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by KyleRosenberg** [719Ben/myCUinfo-API#5]
x = session.get('http://mycuinfo.colorado.edu')
returns the source for the following redirect page

<img width="1680" alt="screen shot 2017-05-12 at 10 59 47 pm" src="https://cloud.githubusercontent.com/assets/5465361/26022600/baccd5bc-3766-11e7-84e1-bdcb1c59fc78.png">

**Comment by KyleRosenberg** [comment]
Sorry, I didnt look at the other issue before posting this. I forked and mostly redid the login flow, however I hope I can get in contact with you because I am running into an issue down the line.

**Comment by biw** [comment]
Hi @KyleRosenberg,

So I was finally able to look into it and have all the login flow done. There are still some issues right now with some of the date items, but if you want to do a pull request, the current branch I'm working off is #6
